name: tron_stake
description: "Stake Tron."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  appsflyer_sdk: ^6.15.1
  bip39_mnemonic: ^3.0.6
  blockchain_utils: ^3.6.0
  cached_network_image: ^3.4.1
  card_loading: ^0.3.2
  connectivity_plus: ^6.0.5
  context_menus: ^2.0.0+1
  contextmenu: ^3.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dart_openai: ^5.1.0
  device_info_plus: ^11.2.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  extended_image: ^9.0.7
  flutter:
    sdk: flutter
  flutter_ads_package: ^1.2.9
  flutter_app_badge: ^2.0.2
  flutter_cache_manager: ^3.4.1
  flutter_highlight: ^0.7.0
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^4.0.0
  flutter_uxcam: ^2.5.6
  get_it: ^8.0.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  http_parser: ^4.0.2
  in_app_review: ^2.0.9
  intl: ^0.19.0
  ionicons: ^0.2.2
  markdown: ^7.2.2
  modal_bottom_sheet: ^3.0.0
  # onesignal_flutter: ^5.2.7
  on_chain: ^4.5.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.3
  persistent_bottom_nav_bar: ^6.2.1
  pretty_qr_code: ^3.3.0
  provider: ^6.0.5
  pull_down_button: ^0.10.1
  purchases_flutter: ^8.3.1
  purchases_ui_flutter: ^8.3.1
  screenshot: ^3.0.0
  scroll_to_index: ^3.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.2.2
  timezone: ^0.10.0
  unicons: ^3.0.0
  url_launcher: ^6.2.6
  url_strategy: ^0.3.0
  uuid: ^4.5.0
  xml: ^6.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo.png
  min_sdk_android: 21
  web:
    generate: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
