class TipsConstants {
  static const List<String> topTeams = [
    "Manchester City",
    "Manchester United",
    "Liverpool",
    "Chelsea",
    "Arsenal",
    "Tottenham Hotspur",
    "Real Madrid",
    "Barcelona",
    "Atletico Madrid",
    "Sevilla",
    "Valencia",
    "Bayern Munich",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    "Juventus",
    "AC Milan",
    "Inter Milan",
    "AS Roma",
    "Napoli",
    "Paris Saint-Germain",
    "Lyon",
    "Marseille",
    "Monaco",
    "Ajax",
    "PSV Eindhoven",
    "Feyenoord",
    "Benfica",
    "Porto",
    "Sporting CP",
    "Zenit Saint Petersburg",
    "CSKA Moscow",
    "Spartak Moscow",
    "Galatasaray",
    "Fenerbahce",
    "Besiktas",
    "Shakhtar Donetsk",
    "Dynamo Kyiv",
    "Celtic",
    "Rangers",
    "Red Bull Salzburg",
    "Olympiacos",
    "Panathinaikos",
    "Copenhagen",
    "Anderlecht",
    "Club Brugge",
    "Standard Liege",
    "Basel",
    "Young Boys",
    "Dinamo Zagreb",
    "Al Ahly",
    "Zamalek",
    "Mamelodi Sundowns",
    "Esperance",
    "Raja Casablanca",
    "Wydad Casablanca",
    "Al Hilal",
    "Al Nassr",
    "Al Ittihad",
    "Al Sadd",
    "Al Duhail",
    "Boca Juniors",
    "River Plate",
    "Independiente",
    "Racing Club",
    "Flamengo",
    "Palmeiras",
    "Santos",
    "Corinthians",
    "Sao Paulo",
    "Gremio",
    "Internacional",
    "Cruzeiro",
    "Atletico Mineiro",
    "Vasco da Gama",
    "America de Cali",
    "Deportivo Cali",
    "Nacional",
    "Peñarol",
    "Colo-Colo",
    "Universidad de Chile",
    "LDU Quito",
    "Emelec",
    "Barcelona SC",
    "Independiente del Valle",
    "Urawa Red Diamonds",
    "Kashima Antlers",
    "Gamba Osaka",
    "Yokohama F. Marinos",
    "Al Jazira",
    "Pachuca",
    "Club America",
    "Cruz Azul",
    "Chivas",
    "Tigres UANL",
    "LA Galaxy",
    "Seattle Sounders",
    "Toronto FC",
    "Atlanta United",
    "New York City FC"
  ];

  static const List<String> topCountries = [
    "Argentina",
    "France",
    "Brazil",
    "Belgium",
    "England",
    "Netherlands",
    "Croatia",
    "Italy",
    "Portugal",
    "Spain",
    "Mexico",
    "Germany",
    "United States",
    "Switzerland",
    "Uruguay",
    "Colombia",
    "Denmark",
    "Senegal",
    "Morocco",
    "Japan",
    "Serbia",
    "Poland",
    "Sweden",
    "South Korea",
    "Austria"
  ];

  static const List<String> topFootballFederations = [
    "FIFA",
    "UEFA",
    "CONMEBOL",
    "CONCACAF",
    "AFC",
    "CAF",
    "OFC",
    "FA",
    "DFB",
    "FIGC"
  ];

  static const List<String> popularLeagues = [
    "Premier League", // Англия
    "La Liga", // Испания
    "Bundesliga", // Германия
    "Serie A", // Италия
    "Ligue 1", // Франция
    "Eredivisie", // Нидерланды
    "Primeira Liga", // Португалия
    "Brasileirão", // Бразилия
    "MLS", // США
    "Super Lig", // Турция
    "Russian Premier League", // Россия
    "J1 League" // Япония
  ];

  static const Map<String, List<String>> popularLeaguesWithCountries = {
    "England": ["Premier League"],
    "Spain": ["Primera Division"],
    "Italy": ["Serie A"],
    "Germany": ["Bundesliga"],
    "France": ["Ligue 1"],
    "Brazil": ["Brasileirão"],
    "Argentina": ["Argentine Primera Division"],
    "Portugal": ["Primeira Liga"],
    "Netherlands": ["Eredivisie"],
    "United States": ["MLS"],
    "Mexico": ["Liga MX"],
    "Belgium": ["Pro League"],
    "Austria": ["Bundesliga"],
    "Switzerland": ["Swiss Super League"],
    "Croatia": ["Croatian First Football League"],
    "Serbia": ["Serbian SuperLiga"],
    "Denmark": ["Danish Superliga"],
    "Sweden": ["Swedish Allsvenskan"],
    "Poland": ["Polish Ekstraklasa"],
    "Uruguay": ["Uruguayan Primera Division"],
    "Colombia": ["Colombian Categoria Primera A"],
    "Japan": ["J1 League"],
    "South Korea": ["K League 1"],
    "Morocco": ["Moroccan Botola Pro"],
    "Senegal": ["Senegal Premier League"]
  };
}
